language: php
env:
- DB=pgsql
php:
- 5.6
- hhvm
matrix:
  exclude:
  - php: hhvm
    env: DB=pgsql
  allow_failures:
  - php: 7.0
  - php: hhvm
before_script:
- if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;"
  -U postgres; fi
- if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres;
  fi
script: phpunit --configuration phpunit_pgsql.xml --coverage-text
deploy:
  provider: cloudfoundry
  api: https://api.cloud.service.gov.uk
  username: nmdsdevopsserviceadm@hotmail.com
  password:
    secure: G1xNsuYXUepoRjnEuBZbhsqi14+O3IzQc5NCiZ53Oxj0fDSiTa47uYL4/U+isUdLuWphAOg6PU/gi81rjPxk91JTdR+bPk3E/en1ygAl/mS4/TzJbhCsr4i2/qqQ2wRi3CooF6bmtc2b/upORJK9xooKG+G5EZrtgqrzK56d0Y6n3/GKGsolgfzPT9V8oeT//CQYv6TcMsu+PCVYdBEjKeuknAqRJXtrfRnssPDntb/3U/5NEjI9c0OU73u12X6MGxi1zKNl0ro26zAVE46uPAO/ta0BaRlYtdjwsEfPES7JMenAL8sluY9OMTFpwDuJeo4loNeJY6/Avxz78XI29IILVqb95w8UbGGwOrchwGXlgN7Nm7k4xJHOBWQalx7OofC4lo1nq+PCjreo6e6QdaeFniwtVExg5iseGsuaGCNmE65vxIKYwsfZpTJBTzfrvP9Bp0vcD+4eMJGLD/ih6NE3NyIcSfz6k/MN+CF7uUlBgCVt3STPfgluNVtoYt6qqcj2tpru+c6DL7SMolhU9v/gqSFKLqpN0A/UAFqlvU9kAPdUfx+McRDJ6HV4slTGenrMDbmiI3wa0jhNKFHgtl+Ge8svM0h6JcAXOr6FlsMl3by2jmXdATDcorCwUl9E0yQXHrOLxwsv5wK1tFf6qRTsp2JKy/3Zf9gM0OViHsM=
  organization: dhsc-skills-for-care-nmds-sc-2
  space: sandbox
  on:
    repo: NMDSdevopsServiceAdm/SopraSteria-SFC-PHP
