# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
env:
  - DB=pgsql
php:
  # using major version aliases

  - 5.6
  # aliased to a recent 7.x version
    # aliased to a recent hhvm version
  - hhvm

# optionally set up exclusions and allowed failures in the matrix
matrix:
  exclude:
    - php: hhvm
      env: DB=pgsql
  allow_failures:
    - php: 7.0
    - php: hhvm
before_script:
  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
script: 
    phpunit --configuration phpunit_pgsql.xml --coverage-text
deploy:
  - provider: cloudfoundry
    edge: true  
    username: nmdsdevopsserviceadm@hotmail.com
    password:
        secure: cKTiahqrFTSeG53wezaKrwgKVYxlbA5r/4UG2BR6GCeYF8LCOaWtkwSnaCdDIn55hNkdmr+/i09NcdfWDrCBtU8KU9jRHnohMKAPSjZ17bBOPtqZpuqsyS/InW+Uc29K70BL3GINfXQaVJEuns8gyNlS1nqj9C0kU2fgI1RmNWDU489zP2vesP/e2Bj1NRWKvpY14B8PU/fZvzvL5Uw1ZYEWPKpAtuuvupVaQGtst/lUtukC52qno5EPuH38dBGQlBUxJBPrWpI/5tn84zB3hNfAp0daQzorZLQdMTrdSMcwD4QsTu6QPJ2cMmrzAA1+ggfr1O7RwiZUVODu2Jpb0JM/ONuEtX+Wonw85ciXuKnnr6HbErzrV/IA58+0YVEwdF6MLMiGli+Y2Bntxa0BLMyIdfLl2N7wXUhSrEgNR8+R3JeJDebTPnnPdY18RKeBRr8c4AxH6C04UdlylOBfB81HlAxYN/l8vDO0MAV22D1PYU4ojJbMamQiT0pxIUp4hWAkBOwa+TNmBpl+4K4d94iMNf3kkjh637WxUgW6fpVFoYM0DEyAHxU+9cB0WPFdDv917l8Wl3DXf2NeT3i8k2xvbQ0UnyV0lHHeYISJnJlKJ9YANXSqr/wCuJu+dB6Yc640PpJCxbcB3DfdUpJadw5KQr+giSw0AJ8UP7NW0aI=
    api: https://api.cloud.service.gov.uk
    organization: dhsc-skills-for-care-nmds-sc-2
    space: sandbox
    manifest: manifest.yml
    on:
        branch: master  